### PR TITLE
Fix for Gradle 8.8

### PR DESCRIPTION
**Pull request by CRogers**
## Before this PR
This plugin fails to work in Gradle 8.8, with the error:

```
Caused by: java.lang.NoSuchMethodError: 'void org.gradle.api.internal.tasks.testing.report.DefaultTestReport.<init>(org.gradle.internal.operations.BuildOperationExecutor)'
	at com.palantir.witchcraft.java.logging.gradle.testreport.TestReportFormattingPlugin.lambda$apply$0(TestReportFormattingPlugin.java:47)
	at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)
```

This plugin does heinous reflection of Gradle internal classes. In 8.8, they [changed the constructor we reflectively access](https://github.com/gradle/gradle/commit/7e3334ea9d32bf8b4930637c66ece2d08282fe05#diff-a3a2553da64f967f904c1b9c403223dd15ba5acd6e3562333ac7e5af78097c63L48-R50), meaning we get the `NoSuchMethodError` for the one we were trying to use.

## After this PR
Either use the new or old constructor depending on the Gradle version.

### CODE REVIEW

File: gradle-witchcraft-logging/build.gradle [hunk 1]
```diff
@@ -45,3 +45,7 @@ pluginBundle {
     description = 'Palantir Witchcraft logging plugins used to improve developer experience building, running, and debugging applications using the witchcraft logging api: https://github.com/palantir/witchcraft-api.'
     tags = ['witchcraft', 'logging', 'idea']
 }
+
+test {
+    systemProperty 'ignoreDeprecations', 'true'
```
Comment (CRogers) [inline gradle-witchcraft-logging/build.gradle:50]: Complains about using `JavaPluginConvention` - but as far as I can see we don't use `.getConvention` or other `JavaPluginConvention` related stuff anyway. The only thing I think it could be is `AbstractTestTask` extends `ConventionTask`, which doesn't seem a big deal.

**Comment by felixdesouza** [comment]
👍
